# Generated by Django 4.1.6 on 2023-02-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='price',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='desc',
            new_name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
